### ISSUE TITLE
Enable defining K8s pullPolicy to kernel image and executor image

### ISSUE THREAD

**Issue by lresende** [jupyter-server/enterprise_gateway#1041]
### Problem

When defining a kernelspec to use SparkOperator we define two images (driver and executor image)

```
  "metadata": {
    "process_proxy": {
      "class_name": "enterprise_gateway.services.processproxies.spark_operator.SparkOperatorProcessProxy",
      "config": {
           "image_name": "foo:dev",
           "executor_image_name": "foo_executor:dev"
      }
    }
```

during development in non-prod environments, it's very common to update images to a container repository with the same tag (e.g. dev). When this occurs, there is a need to define the pullPolicy to Always to enable refreshing these container images on the environment. 

Based on this, we should add the capability to define the pullPolicy to apply to these images.

**Comment by kevin-bates** [comment]
Yeah, per our previous conversation, it does seem like we could add a pull policy to the kernel-pod template although I would suggest just updating the already [configurable pull policy on the KIP (Kernel Image Puller)](https://github.com/jupyter-server/enterprise_gateway/blob/54c8e31d9b17418f35454b49db691d2ce5643c22/etc/kubernetes/helm/enterprise-gateway/values.yaml#L87-L92).

Also keep in mind that if this is not done via the KIP, then you will likely incur launch timeouts or need to adequately adjust (increase) your timeouts to include image download.  With KIP there's a higher probability that won't be necessary.  But given this is "development in non-prod environments", you can also tolerate those kinds of issues .

Sure seems like KIP is the solution here.  Is there a reason this isn't satisfactory and what would you suggest that might work better (and easier)?

**Comment by kevin-bates** [comment]
Closing since this functionality is [already provided by the Kernel Image Puller](https://github.com/jupyter-server/enterprise_gateway/blob/252b02f095e9c2a5e51bdde97fdc0126bc96b4ac/etc/docker/kernel-image-puller/kernel_image_puller.py#L22-L26).  If that functionality is not sufficient, we can re-open the issue.
