### ISSUE TITLE
Can I specify which node I start the kernel on?

### ISSUE THREAD

**Issue by LeeMoonCh** [jupyter-server/enterprise_gateway#1062]
If I have three remote nodes, I want to specify that the kernel should be started at a certain node when I start the kernel.
Is there any way?

**Comment by rahul26goyal** [comment]
Hi @LeeMoonCh 
are you looking for scheduling of the kernel on Kubernetes runtime?

**Comment by LeeMoonCh** [comment]
Already, I have an idea to control the acquisition of remote ip through KRENEL_* instead of round robin.
Thank @rahul26goyal

**Comment by kevin-bates** [comment]
If you're using the [`DistributedProcessProxy`](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/deploy-distributed.html#distributed-deployments) and want a specific kernel to always run on a specific node (or set of nodes) you can configure nodes for _that_ kernel directly in the `kernel.json` file via the `remote_hosts` configuration.

If you're looking to swap out the round-robin algorithm used by `DistributedProcessProxy` to use a value conveyed via `KERNEL_`,  please consider making a contribution that allows for that portion of `DistributedProcessProxy` to be configured, as that is an item on our [wish list](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/contributors/roadmap.html#wish-list).

If this is a `KubernetesProcessProxy`, you might try adding [some aspect of node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) to your `kernel-pod.yaml.j2` file that can utilize some `KERNEL_` value or other aspect of the kernel.

We'd love to hear about the solution you come up with.  Thanks.

**Comment by kevin-bates** [comment]
Hi @LeeMoonCh, I'm going to re-open this issue since #1068 will be addressing this.  Thank you.
