### ISSUE TITLE
Setting up local development environment (pip, conda, pipenv, etc) 

### ISSUE THREAD

**Issue by bloomsa** [jupyter-server/enterprise_gateway#1098]
Help us improve the Jupyter Enterprise Gateway project by reporting issues
or asking questions.

## Description
Hi all, I'm working on setting up my IDE and local environment with all of the required packages so I can eventually debug EG with breakpoints. (for code exploration purposes) I had some issues getting this set up and I'm wondering if recent changes to the codebase have left this process behind a bit. 

In #1079 the steps to build a conda environment for the project were removed without a replacement process. Some sort of environment, whether it be conda, pipenv, venv, or just the local python environment, containing the required packages for the project is needed in order to run the app and debug. [requirements.yml ](https://github.com/jupyter-server/enterprise_gateway/blob/5b6970daf19e3b07dfd9efb47f7714639182600c/requirements.yml) is still around with a listing of the required packages, but as far as I can tell, only conda knows how to use this. 

For my personal setup, I decided to use pipenv for my python environment. As prerequisite to that, I built the conda env based on `requirements.yml` 

> `conda env create --file requirements.yml --name eg`

I then activated the conda env so that I could generate a requirements.txt by using the following command

> `pip list --format=freeze > requirements.txt` 

From here, I deactivated the conda env and was able to run `pipenv install -r requirements.txt` to generate a Pipfile, Pipfile.lock, and the venv with all required packages. At this point, I'm all setup to run/debug the code in PyCharm.

Let me know if I'm missing something that would have made this easier. If not, I would be happy to contribute and document my process more formally than in this Issue
## Screenshots / Logs

If applicable, add screenshots and/or logs to help explain your problem.
To generate better logs, please run the gateway with `--debug` command line parameter.

## Environment

- Enterprise Gateway Version 2.6.0 (latest)
- Platform: local (macOS laptop)
- PyCharm IDE for code exploration

## Reference
[Process used to generate requirements.txt from conda env](https://stackoverflow.com/a/57845418)

**Comment by kevin-bates** [comment]
Hi @bloomsa.  Yeah, we should probably restore the doc for how to build the conda env and could even restore the make target. What I think should remain removed though is the forced usage of an env on every other makefile target. 
I'm afk until next Wednesday so can't deal with this sooner. If you'd like to create a pr to restore those portions that would be great.

**Comment by bloomsa** [comment]
That makes sense, you got it 👍
