### ISSUE TITLE
Interrupts not working on PySpark Kernel

### ISSUE THREAD

**Issue by SamRanjha** [jupyter-server/enterprise_gateway#1112]
## Description
Jupyter Notebook allows user to interrupt the cell execution by sending the interrupt command. But when we are using PySpark Kernel and we interrupt a cell execution, even though the kernel becomes idle on the UI but in the background the job keeps on executing. So, since the UI is idle we can send new commands and the kernel goes to busy but in the driver the old job keep on executing and the execution of the new job starts only after the first job execution is finished.
We do receive signum : 2 in logs for the "launch_ipykernel.py" but the execution continues.
Thus, the interrupt feature is broken for PySpark Kernels.

## Reproduce
1. Start a long running job on Jupyter Notebook.
2. Interrupt the job.
<img width="1536" alt="Screenshot 2022-06-13 at 9 00 01 PM" src="https://user-images.githubusercontent.com/30014834/173390800-f248bb05-6304-4a0e-b19b-7c10fc1c5362.png">

<img width="1178" alt="Screenshot 2022-06-13 at 9 03 53 PM" src="https://user-images.githubusercontent.com/30014834/173390599-82e1f8a2-1ca6-4840-9cc7-67fa47c2c691.png">

3. The kernel becomes idle but the job keeps on executing.
4. The execution gets completed in the driver logs.
<img width="1433" alt="Screenshot 2022-06-13 at 9 06 38 PM" src="https://user-images.githubusercontent.com/30014834/173391081-314a9965-06c3-435f-a51f-d349aaae8c33.png">
5. Until the previous execution is completed, we don't receive output for the next executions.
Eg - This job took more than three minutes which usually get executed in seconds.
<img width="1175" alt="Screenshot 2022-06-13 at 9 10 40 PM" src="https://user-images.githubusercontent.com/30014834/173392144-15a0315b-2a8c-424c-83a9-f166483fa610.png">

## Expected behavior
The job should have stopped execution once the interrupt signal was received.

## Context

- Operating System and version: Kubernetes v1.21.12

- Browser and version: Firefox, 91.10.0esr (64-bit)
- Jupyter Notebook version:  6.4.11

<details><summary>Command Line Output</summary>
<pre>
JEG 
[I 220613 15:29:50 web:2243] 200 GET /api/swagger.json (192.168.163.57) 0.82ms
[I 220613 15:29:50 web:2243] 200 GET /api/swagger.json (192.168.133.171) 0.76ms
[I 220613 15:29:50 web:2243] 200 GET /api/swagger.json (192.168.117.61) 0.75ms
[I 2022-06-13 15:29:56.073 EnterpriseGatewayApp] validating incoming request: POST: /api/kernels/94bea8dd-be62-467f-b3f6-15960d81acbb/interrupt
[I 2022-06-13 15:29:56.073 EnterpriseGatewayApp] successfully validated request: /api/kernels/94bea8dd-be62-467f-b3f6-15960d81acbb/interrupt
[I 2022-06-13 15:29:56.074 EnterpriseGatewayApp] Kernel interrupted: 94bea8dd-be62-467f-b3f6-15960d81acbb
[I 220613 15:29:56 web:2243] 204 POST /api/kernels/94bea8dd-be62-467f-b3f6-15960d81acbb/interrupt (127.0.0.1) 2.00ms
[I 2022-06-13 15:30:01.973 EnterpriseGatewayApp] validating incoming request: GET: /api/kernels

PySpark driver
582-22/06/13 15:29:56 INFO TaskSetManager: Finished task 231.0 in stage 0.0 (TID 231) in 9 ms on 192.168.9.112 (executor 1) (231/20000)
583-22/06/13 15:29:56 INFO TaskSetManager: Finished task 229.0 in stage 0.0 (TID 229) in 52 ms on 192.168.74.254 (executor 2) (232/20000)
584-22/06/13 15:29:56 INFO TaskSetManager: Starting task 234.0 in stage 0.0 (TID 234, 192.168.74.254, executor 2, partition 234, PROCESS_LOCAL, 7352 bytes)
585-22/06/13 15:29:56 INFO TaskSetManager: Finished task 233.0 in stage 0.0 (TID 233) in 7 ms on 192.168.74.254 (executor 2) (233/20000)
586-22/06/13 15:29:56 INFO TaskSetManager: Starting task 235.0 in stage 0.0 (TID 235, 192.168.74.254, executor 2, partition 235, PROCESS_LOCAL, 7352 bytes)
587-22/06/13 15:29:56 INFO TaskSetManager: Finished task 234.0 in stage 0.0 (TID 234) in 11 ms on 192.168.74.254 (executor 2) (234/20000)
588:[I 2022-06-13 15:29:56,074.074 launch_ipykernel] gateway_listener got request: {'signum': 2}
589-22/06/13 15:29:56 INFO TaskSetManager: Finished task 232.0 in stage 0.0 (TID 232) in 48 ms on 192.168.9.112 (executor 1) (235/20000)
590-22/06/13 15:29:56 INFO TaskSetManager: Starting task 236.0 in stage 0.0 (TID 236, 192.168.9.112, executor 1, partition 236, PROCESS_LOCAL, 7352 bytes)
591-22/06/13 15:29:56 INFO TaskSetManager: Starting task 237.0 in stage 0.0 (TID 237, 192.168.9.112, executor 1, partition 237, PROCESS_LOCAL, 7352 bytes)
592-22/06/13 15:29:56 INFO TaskSetManager: Finished task 236.0 in stage 0.0 (TID 236) in 9 ms on 192.168.9.112 (executor 1) (236/20000)
593-22/06/13 15:29:56 INFO TaskSetManager: Finished task 237.0 in stage 0.0 (TID 237) in 8 ms on 192.168.9.112 (executor 1) (237/20000)
594-22/06/13 15:29:56 INFO TaskSetManager: Starting task 238.0 in stage 0.0 (TID 238, 192.168.9.112, executor 1, partition 238, PROCESS_LOCAL, 7352 bytes)

</pre>
</details>

**Comment by rahul26goyal** [comment]
@kevin-bates : this is the other issue we discussed last week. I think the proposal @SamRanjha  is making makes sense to me. 
pls share ur thoughts on this.

**Comment by kevin-bates** [comment]
Hi @SamRanjha and @rahul26goyal.  Yes, I think this makes sense (both the issue and its proposed resolution).  I'm not very knowledgeable about discovering and interacting with spark jobs.

Looking at the various example URLs, it appears we'd need the `spark_ui_port` and the `application_id`.  Since we create the spark context, I believe the `application_id` can be obtained from the context, but I'm not certain about the UI port but I think it too is available.  We need to try to introduce as few additional arguments as possible - preferably none.

Question: Once the application/jobs are killed, what is the expectation of the _next_ spark operation?  Is the context still valid and things will "just work"?  (This question probably shows my Spark naivete so I apologize in advance.)

cc: @lresende

**Comment by lresende** [comment]
> Question: Once the application/jobs are killed, what is the expectation of the _next_ spark operation? Is the context still valid and things will "just work"? (This question probably shows my Spark naivete so I apologize in advance.)

I have the same question, but from some quick experiments, it seems that we will kill existing jobs but the context will still be up for starting new jobs, having said that, we should make this test part of the success criteria for this issue. 

Also, is there any spark utility that does what we need, mainly to avoid us having to maintain it in new Spark releases  (e.g. https://sparkbyexamples.com/spark/spark-how-to-kill-running-application/#:~:text=Opening%20Spark%20application%20UI.,kill%20to%20stop%20the%20Job)

**Comment by rahul26goyal** [comment]
hi @kevin-bates 
I think we can close this ticket now as the PR is merged?

**Comment by kevin-bates** [comment]
Good point - thanks @rahul26goyal.
