### ISSUE TITLE
Finalize disposition of k8s deployment script enterprise-gateway.yaml

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#1120]
In looking at #1119 I notice it (correctly) removes the _empty_ file [`etc/kubernetes/enterprise-gateway.yaml`](https://github.com/jupyter-server/enterprise_gateway/blob/main/etc/kubernetes/enterprise-gateway.yaml).  This file was deleted in #1073, but then came back as an empty file in #559 (probably due to some merge/rebase snafu).

Looking at #1073, there was no discussion of its removal, which is why I was curious to see its "deletion" in #1119.

Since we're preparing for a major release (3.0) and its existence was a bit problematic because it introduced two locations for deployment configurations, I'm okay with stating that Helm is the only kubernetes deployment route for EG.  (As a reference point, JupyterHub only provides Helm deployment as well - so, in that sense, there's precedent.)

However, in looking at the docs, we still reference `enterprise-gateway.yaml` in the following files:
```
contributors/system-architecture.md
contributors/docker.md
operators/config-add-env.md
operators/deploy-kubernetes.md
```

So, I think we should have the following discussion: _Should we continue to support (and bring back) `enterprise-gateway.yaml`?_
- If not, we need to clean up the existing references in the docs.  Some will be replaced with corresponding references to helm chart files and others will be removed directly.
- If we decide to restore the file, then we'll need to be sure the equivalent functionality is listed (either directly or commented-out) and the applicable docs are updated.

As a voting mechanism, we can use:
:+1:: "_yes, remove `enterprise-gateway.yaml` and its references_"
:-1:: "_no, let's restore `enterprise-gateway.yaml` and ensure its complete_"

cc: @lresende, @rahul26goyal, @akchinSTC, and anyone else with skin in the K8s-EG game.

**Comment by kevin-bates** [comment]
Now that #1119 is merged, the link-checker is failing during CI because of the references to the deleted `etc/kubernetes/enterprise-gateway.yaml` file.

**Comment by darkstarmv** [comment]
`etc/kubernetes/enterprise-gateway.yaml` is not needed - all k8s deployment files are managed in one place - helm chart. 
Users have an option to deploy with `helm` or `kubectl` by generating yaml files with `helm template` command.
If you do decide to restore `etc/kubernetes/enterprise-gateway.yaml` you will need to keep it in sync with helm chart files.

**Comment by kevin-bates** [comment]
Hi @darkstarmv - thank you for responding.  I completely agree with all that you said.  

Since the period for response has passed, I'm going to close this issue and we'll use a single source of truth for k8s deployments. #1123 has been merged to remove the previous references to the script.
