### ISSUE TITLE
Kernel variables are override by variable from gateway in Kubernetes

### ISSUE THREAD

**Issue by jeremythuon** [jupyter-server/enterprise_gateway#1220]
## Description

Since the change https://github.com/jupyter-server/enterprise_gateway/pull/1164 , the kernel inherits all the variables present in the gateway pod.
This can override variables already configured on the kernel image

Print var on Kernel and you have all the variables present on the gateway

eg. : 
The JEG image has Java installed with its environment variables (JAVA_HOME). With a custom Spark image that uses a different Java. The kernel launch script will override this variable

## Expected behavior
Be able to filter the variables to be given or exclude all variables by default from the gateway

**Comment by jeremythuon** [comment]
Use JEG 3.0.0
Need to upgrade to 3.1.0

**Comment by kevin-bates** [comment]
I think you raise an interesting point.  I'm just not sure how to determine which envs are _configured_ into a given image.  One way to work around this would be to define _conflicting_ envs in the `kernel.json` `env:` stanza.  Then, the launcher will be instantiated with those in its environment and flow the "current environment" to the container.
