### ISSUE TITLE
could not find elyra/enterprise-gateway:3.2.1

### ISSUE THREAD

**Issue by capacman** [jupyter-server/enterprise_gateway#1275]
3.2.1 version helm chart referring to "elyra/enterprise-gateway:3.2.1" image but it seems that it is not published.

**Comment by kevin-bates** [comment]
@lresende - I only [see `3.2.1` tags](https://hub.docker.com/orgs/elyra/repositories) for the kernel images and `kernel-image-puller`, but not `enterprise-gateway`.  Can you please push a multi-arch `elyra/enterprise-gateway:3.2.1` image?

**Comment by lresende** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/382917/223866433-a838f0a4-c521-416b-b515-129b4e88d597.png">

**Comment by kevin-bates** [comment]
Thank you Luciano!
