### ISSUE TITLE
Add Mutual Authentication Option as a Parameter

### ISSUE THREAD

**Issue by s4mukka** [jupyter-server/enterprise_gateway#1319]
### Problem
Currently, Jupyter Server only supports "REQUIRED" mutual authentication on YARN, which may not be sufficient for some use cases. For example, in scenarios where mutual authentication is not required to establish a secure connection between the server and clients, there is no built-in way to configure this in Enterprise Gateway.

### Proposed solution
I suggest adding an option to the Jupyter Server configuration that allows users optional mutual authentication. When introducing this feature, users can specify with REQUIRED, OPTIONAL or DISABLED. This enhancement would greatly improve user configuration freedom.

### Additional Context
We were unable to configure the YARN endpoint to authenticate with Kerberos. We also tried to use simple authentication but the "hadoop.auth" cookie is not being returned. We know that these errors that we got would be due to some missing configuration in YARN, but we believe that the Enterprise Gateway should also allow this authentication as an option.

I believe that implementing this feature would benefit the freedom of configuration for Enterprise Gateway.

**Comment by s4mukka** [comment]
#1320

**Comment by lresende** [comment]
Fixed by #1320
