### ISSUE TITLE
Fix doc build

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#1329]
The link check is [failing the docs build](https://github.com/jupyter-server/enterprise_gateway/actions/runs/6152127288/job/16693648668?pr=1327) due to the following:
```
FAILED etc/docker/kernel-tf-py/README.md::/home/runner/work/enterprise_gateway/enterprise_gateway/etc/docker/kernel-tf-py/README.md <a href=https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook>
```

It appears that https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook is no longer a valid link.  This may imply that the `tensorflow-notebook` has moved, changed names, no longer supported, etc., which may have an impack on the `kernel-tf-py` image.  So that aspect of things should be considered when addressing this issue.

**Comment by fresende** [comment]
This has been moved to a different directory, let me submit a pull request with updated link.
