### ISSUE TITLE
image not found for 3.2.3 release

### ISSUE THREAD

**Issue by edwardzjl** [jupyter-server/enterprise_gateway#1371]
## Description

When I try to deploy enterprise gateway 3.2.3 through helm I encountered ErrImagePull error。

And I then checked docker hub it seems that 3.2.3 images has not been published yet.

**Comment by lresende** [comment]
There was an image that was broken that failed the build, should be resolved now... I will send couple of prs to fix the issues...

**Comment by paf91** [comment]
![image](https://github.com/jupyter-server/enterprise_gateway/assets/12195041/2d463faa-1843-4a0d-abc8-294e5bd8288d)
Still no image on dockerhiub, getting error while trying to pull images
![image](https://github.com/jupyter-server/enterprise_gateway/assets/12195041/d9f0a21f-78bc-4a36-8f14-15d8c877189a)

**Comment by lresende** [comment]
![image](https://github.com/jupyter-server/enterprise_gateway/assets/382917/e9ed12c3-fee2-40b9-8ad7-b47be308151f)

**Comment by paf91** [comment]
im getting exec /usr/bin/tini: exec format error error using this image. what architecture it's using?
