### ISSUE TITLE
Executing a Kernel/iPython startup script 

### ISSUE THREAD

**Issue by amangarg96** [jupyter-server/enterprise_gateway#838]
## Description
I am using EG 2.1.1 in YARN cluster mode. I want to catch certain spark job exceptions (like executor running OOM, max result size threshold exceed) and raise my own custom exceptions which are easily interpretable by the users. 

For this, I found [this](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.InteractiveShell.set_custom_exc) method which allows to create a handler which is called when an exception is raised. 
So in short, I get the iPython interactive shell using get_ipython(), and then create a handler for the exception. This code needs to be run at the beginning of every notebook.

```
def custom_exc(shell, etype, evalue, tb, tb_offset=None):
     .....

get_ipython().set_custom_exc((Exception,), custom_exc)

```
Currently, I am adding this code at the beginning of my notebook (.ipynb), and after running it I am getting the desired result. Is there a way to run this as a startup script while launching a kernel? 

I tried making it part of the launch_ipykernel.py file, by adding the code before embed_kernel() call but it didn't work. Please let me know if I should share the code snippet, if the description of the problem is not clear.  

## Environment
- Enterprise Gateway Version [2.1.1]
- Platform: [YARN Cluster mode]
- Others [Jupyter Server 5.7.8, JupyterLab 0.33.12]

**Comment by kevin-bates** [comment]
> Is there a way to run this as a startup script while launching a kernel?

I don't know and don't have bandwidth to try to figure stuff like this out.  If you need this in the launch script, you'll need to provide a pull request.  This is a feature request and one that needs to be provided by the community due to lack of maintainers on this project.

**Comment by santosh-d3vpl3x** [comment]
In `start_ipython` in `launch_ipykernel.py` you should include following snippet just before `embed_kernel(local_ns=namespace, **kwargs)`
```python

    from ipykernel.ipkernel import IPythonKernel
    from ipykernel.kernelapp import IPKernelApp

    class MyCustomKernel(IPythonKernel):
        def __init__(self, **kwargs):
            self.shell.set_custom_exc((Exception,), custom_exc)

    IPKernelApp.kernel_class = MyCustomKernel    
```

**Comment by kevin-bates** [comment]
Thank you @santosh-d3vpl3x.

I think for this to be generally useful, we'd want to "plumb" a "kernel_class_name" parameter that the launcher can detect and set.  This value could then be specified in the kernel.json:metadata:process_proxy:config stanza.   The other option is to bake it into launch_ipykernel.py directly, but then you run the risk of losing the change (or having to repeat the update) on each software revision.  The other thing to consider is that this handler class would also need to be deployed wherever launch_ipykernel is deployed.

I'm willing to help guide getting these hooks in place if someone would like to contribute an initial pull request.

**Comment by santosh-d3vpl3x** [comment]
Indeed, I think that'd be extensible approach to solve this for most of the parts. I could definitely help with this.

**Comment by kevin-bates** [comment]
Excellent.  We should also decide whether a configured, but missing, class name should fail the request, or we (log and) continue without it as best we can.  I'm thinking the former for now but handling its absence in a graceful manner.

Folks that want to take advantage of this particular feature must also update the respective kernel images to contain their implementation, etc., so there's a fair amount of "on-site" integration/deployment necessary that will require documentation.

Thank you for your help @santosh-d3vpl3x.  

@amangarg96 - if you're unable to contribute at this time, please stay close by so you can help drive this and get the feature you desire as well.

**Comment by amangarg96** [comment]
Thanks @santosh-d3vpl3x, the solution you suggested worked. I agree with Kevin on making it extensible. 
Unfortunately, I do not have the bandwidth to contribute at this time, but I can help as much as I can.

**Comment by santosh-d3vpl3x** [comment]
FWIW, For quicker turn around, we could add a "feature flag" for config to let users choose what'd they want to do in case the required module is missing. `strict` mode will make kernels to fail but a `non-strict` mode will log a warning and move on.

**Comment by kevin-bates** [comment]
True, although all of that would also need to be conveyed to the launcher and I'd prefer we keep parameters to a minimum.  In addition, I suspect there's a reason for folks using a start script in the first place and something might fail downstream when trying to continue anyway.  

My feeling is if they went through the work of configuring this, then we should be strict.  If there happens to be a strong demand for a more tolerant behavior, then we can entertain that at that time.  Does that sound okay?

**Comment by kevin-bates** [comment]
Closing via #1076.
