### ISSUE TITLE
Add typing hints to kernel management and handlers

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#848]
Part of the larger [umbrella issue](https://github.com/jupyter/enterprise_gateway/issues/847) this issue will track adding typing hints to the manager and handlers located in `enterprise_gateway/services/kernels`.

**Comment by rahul26goyal** [comment]
@kevin-bates : I can work on these if someone could guide with it.
I hav no prior experienc with JEG but wiling to learn and contribute :)

**Comment by kevin-bates** [comment]
Hi @rahul26goyal - thank you for your interest in contributing to EG!  I will be happy to help you with this issue.

If you have any questions on a given type or where to locate things, just ping this issue.  I think you'll find most of the uses of this stuff occurs in the [jupyter_client](https://github.com/jupyter/jupyter_client) repo.  However, any process-proxy references will be in the [processproxies](https://github.com/jupyter/enterprise_gateway/tree/master/enterprise_gateway/services/processproxies) sub-package in EG.
