### ISSUE TITLE
Add typing hints to process proxies

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#851]
Part of the larger [umbrella issue](https://github.com/jupyter/enterprise_gateway/issues/847) this issue will track adding typing hints to the process proxies located in `enterprise_gateway/services/processproxies`.

**Comment by bloomsa** [comment]
I can do this one @kevin-bates

**Comment by kevin-bates** [comment]
Fantastic! Thanks Sam.

**Comment by kevin-bates** [comment]
Closing via #1129 - thank you @bloomsa!
