### ISSUE TITLE
Use different tags for test related docker images

### ISSUE THREAD

**Issue by lresende** [jupyter-server/enterprise_gateway#862]
Using dev does not allow for consistent test reproducibility, a different tag (such as a timestamp) would allow for better reproducibility as old builds can still be re-run based on old images.

**Comment by kevin-bates** [comment]
In a side-bar, we decided to tag `demo-base` with the version of Spark for now.  Also discussed commit hashes and date stamps.

**Comment by kevin-bates** [comment]
@lresende - is this an issue worth dealing with and, if so, do you have ideas for how to address this?  I usually just retag local images and push the retagged images for use in k8s, etc.

**Comment by kevin-bates** [comment]
@lresende, I'm going to close this as I believe the underlying issue was addressed.  Please re-open, along with more details of what images need to be tagged differently.  Thank you.
