### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/enterprise_gateway#881]
Enterprise Gateway documentation spans various roles and forms for information.  It would be helpful to have this reorganized based on a consumer's role.  Something similar to how the [Jupyter Server](https://jupyter-server.readthedocs.io/en/latest/) or [Zero to JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/#zero-to-jupyterhub-with-kubernetes) docs would be nice.

Sections for Users, Operators, Developers and Contributors would be nice - similar to [this](https://jupyter-server.readthedocs.io/en/latest/#table-of-contents).

**Comment by ashvinnihalani** [comment]
I can start on this. I have some time this weekend

**Comment by kevin-bates** [comment]
Thank you Ashvin!  

It has just come to my attention that the **Project Jupyter Contributor Documentation** link in our [contributing page](https://github.com/jupyter/enterprise_gateway/blob/master/docs/source/contrib.md) is broken.  It should be: https://jupyter.readthedocs.io/en/latest/contributing/content-contributor.html and I'm hoping you could add that to your list.  

It looks like the readthedocs.io links now include a language-code indicator in their URLs now, so it might be good to check for others as well.

**Comment by kevin-bates** [comment]
Hi @ashvinnihalani - how is this coming along?  Are you able to make this contribution?

**Comment by ashvinnihalani** [comment]
Yeah sorry progress has been slow due to some external factors. I can make a PR this weekend, so there is better visibility into progress and we can also have feedback on some visual elements.

**Comment by kevin-bates** [comment]
No worries, there are many external factors these days. A working PR would be fantastic! Thank you.

**Comment by kevin-bates** [comment]
Just letting others know that I'm currently doing this and should have something next week.  Thanks.

**Comment by kevin-bates** [comment]
Closing via #1040.
