### ISSUE TITLE
There are some incorrect links in the DockerHub description.

### ISSUE THREAD

**Issue by taeyeopkim1** [jupyter-server/enterprise_gateway#968]
## Description
Hello.
In fact, this is what I found while looking for a solution to [#962](https://github.com/jupyter/enterprise_gateway/issues/962).

The link for "enterprise-gateway-swarm.sh" and "enterprise-gateway-docker.sh" in "https://hub.docker.com/r/elyra/enterprise-gateway/" seems to be connected incorrectly.

https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway-swarm.sh
https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway-docker.sh

When I connect, I can see the NotFound page.
I don't know where to ask, so I post this issue.

## Screenshots / Logs
- Screenshot 1
![image](https://user-images.githubusercontent.com/43223381/117165273-4f623000-ae00-11eb-96a8-baefe0035ee4.png)

- Screenshot 2
![image](https://user-images.githubusercontent.com/43223381/117165443-74ef3980-ae00-11eb-9c2e-692898d32f3a.png)

## Environment

- Enterprise Gateway Version []
- Platform: [DockerHub]
- Others []

**Comment by kevin-bates** [comment]
What version of the docs are you looking at?  I don't find these sections in any of the recent versions.
That said, we do have outstanding references to `enterprise-gateway-swarm.sh` in [`kernel-docker.md`](https://github.com/jupyter/enterprise_gateway/blob/master/docs/source/kernel-docker.md#dockerprocessproxy) and [`docker.md`](https://github.com/jupyter/enterprise_gateway/blob/master/docs/source/docker.md#elyraenterprise-gateway) that should be appropriately replaced with [`docker-compose.yml`](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/docker-compose.yml).

**Comment by taeyeopkim1** [comment]
Well..  What I found was just an overview.
Would this screenshot help?

![image](https://user-images.githubusercontent.com/43223381/117229550-31271f00-ae56-11eb-9f7d-4b3411d4bad7.png)

**Comment by kevin-bates** [comment]
Ah - of course - this is completely helpful - thank you.  This file is located here: https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway/README.md, which we would then update on hub.

Given you've been exercising the docker deployments lately, are you interested in correcting these issues?  (It would be greatly appreciated!)

**Comment by taeyeopkim1** [comment]
I found the files in the link below.

https://github.com/jupyter/enterprise_gateway/blob/remove-python-2.x/etc/docker/enterprise-gateway-docker.sh
https://github.com/jupyter/enterprise_gateway/blob/remove-python-2.x/etc/docker/enterprise-gateway-swarm.sh

Can I simply add those files in the "master" branch?
I would like to provide a pull request, but if it is not what you intended, I will close the pull request.

**Comment by kevin-bates** [comment]
Hi @taeyeopkim1.  The files you're trying to add are obsolete.  Instead, we should update the instructions to deploy kernels in Docker and DockerSwarm to use the docker-compose.yml file and update the previously mentioned locations.  Once the enterprise-gateway README.md is updated (along with the doc entries), we can update the docker hub entry with that content.

**Comment by taeyeopkim1** [comment]
I understand what you mean.
It will take some time.
I will try but It is ok to proceed before me.
Thank you.

**Comment by bloomsa** [comment]
Hi @kevin-bates, I can take this one. can you please assign this to me?

**Comment by kevin-bates** [comment]
Done.  Thank you @bloomsa!

**Comment by kevin-bates** [comment]
Closing via #1049.
